# api-gateway/swagger.yaml
openapi: 3.0.0
info:
  title: API Gateway
  description: Entry point for all notification requests
  version: 1.0.0
  contact:
    name: API Support
    email: support@company.com

servers:
  - url: http://localhost:8000/api
    description: Development server

paths:
  /notifications/email:
    post:
      summary: Send email notification
      description: Validates and queues an email notification
      tags:
        - Notifications
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailNotificationRequest'
      responses:
        '202':
          description: Notification accepted and queued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /notifications/push:
    post:
      summary: Send push notification
      description: Validates and queues a push notification
      tags:
        - Notifications
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushNotificationRequest'
      responses:
        '202':
          description: Notification accepted and queued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
        '400':
          description: Invalid request

  /notifications/status/{notification_id}:
    get:
      summary: Get notification status
      description: Retrieve the status of a previously submitted notification
      tags:
        - Notifications
      parameters:
        - name: notification_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '404':
          description: Notification not found

  /health:
    get:
      summary: Health check
      description: Check API Gateway health status
      tags:
        - System
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    EmailNotificationRequest:
      type: object
      required:
        - user_id
        - template_id
      properties:
        user_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        template_id:
          type: string
          example: "welcome_email"
        variables:
          type: object
          additionalProperties:
            type: string
          example:
            name: "John Doe"
            order_id: "12345"
        idempotency_key:
          type: string
          description: Unique key to prevent duplicate notifications

    PushNotificationRequest:
      type: object
      required:
        - user_id
        - template_id
      properties:
        user_id:
          type: string
          format: uuid
        template_id:
          type: string
          example: "order_update"
        variables:
          type: object
          additionalProperties:
            type: string
          example:
            title: "Order Shipped"
            message: "Your order #123 has been shipped"
        idempotency_key:
          type: string

    NotificationResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            notification_id:
              type: string
              format: uuid
            status:
              type: string
              enum: [queued, processing, sent, failed]
            estimated_delivery:
              type: string
              format: date-time
        message:
          type: string
          example: "Notification queued successfully"
        meta:
          type: object

    StatusResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            notification_id:
              type: string
              format: uuid
            status:
              type: string
              enum: [queued, processing, sent, failed, delivered]
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
            delivery_info:
              type: object
        message:
          type: string
        meta:
          type: object

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: "healthy"
        timestamp:
          type: string
          format: date-time
        service:
          type: string
          example: "api-gateway"
        dependencies:
          type: object
          properties:
            rabbitmq:
              type: string
              example: "connected"
            redis:
              type: string
              example: "connected"

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "Invalid user_id"
        message:
          type: string
          example: "Validation failed"
        meta:
          type: object